---
- mysql_user: name=zabbix password=password priv=*.*:ALL,GRANT state=present
  sudo: yes
  tags: 
    - setup
    - mysql

- mysql_db: name='{{ zabbix_server_db_name }}' state=present
  sudo: yes
  tags: 
    - setup
    - mysql

- mysql_db: name='{{ zabbix_server_db_name }}' state=import target='{{ zabbix_schema }}'/schema.sql.gz
  sudo: yes
  ignore_errors: yes
  tags: 
    - setup
    - mysql

- mysql_db: name='{{ zabbix_server_db_name }}' state=import target='{{ zabbix_schema }}'/images.sql.gz
  sudo: yes
  ignore_errors: yes
  tags: 
    - setup
    - mysql

- mysql_db: name='{{ zabbix_server_db_name }}' state=import target='{{ zabbix_schema }}'/data.sql.gz
  sudo: yes
  ignore_errors: yes
  tags: 
    - setup
    - mysql


- name: Restarting mysql
  service: name=mysql state=restarted
  sudo: yes
  tags:
    - setup
    - mysql


- name: Restarting zabbix
  service: name=zabbix-server state=restarted
  sudo: yes
  tags:
    - setup
    - mysql